Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64" 
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    config.vm.define "ansible" do |ansible|
        ansible.vm.box_download_insecure = true
        ansible.vm.network "public_network", ip: "192.168.1.20" 
        ansible.vm.provision "shell", inline: "echo 'nameserver 8.8.8.8' | sudo tee /etc/resolv.conf > /dev/null"
        ansible.vm.provision "shell", inline: "cp /vagrant/teste-chave  /home/vagrant && \
          chmod 600 /home/vagrant/teste-chave && \
          chown vagrant:vagrant /home/vagrant/teste-chave"
        
        #instala o ansible na vm
        ansible.vm.provision "shell", 
          inline: "apt-get update && \
            apt-get install -y software-properties-common && \
            apt-add-repository --yes --update ppa:ansible/ansible && \
            apt-get install -y ansible"
    end

    config.vm.define "wordpress" do |wordpress|
        #resolver problema SSL
        wordpress.vm.box_download_insecure = true
        wordpress.vm.box = "ubuntu/trusty64"
        wordpress.vm.network "private_network", ip: "172.17.177.40"
        wordpress.vm.synced_folder "./configs", "/configs"      
        wordpress.vm.provision "shell", inline: "touch .ssh/authorized_keys && cat /configs/teste-chave.pub >> .ssh/authorized_keys"      
        wordpress.vm.provision "shell", inline: "echo 'nameserver 8.8.8.8' | sudo tee /etc/resolv.conf > /dev/null"
    end

    config.vm.define "mysql" do |mysql|
      mysql.vm.box_download_insecure = true
      mysql.vm.box = "ubuntu/trusty64"
      mysql.vm.network "private_network", ip: "172.17.177.43"
      mysql.vm.provision "shell", inline: "touch .ssh/authorized_keys && cat /vagrant/configs/teste-chave.pub >> .ssh/authorized_keys"      
      mysql.vm.provision "shell", inline: "echo 'nameserver 8.8.8.8' | sudo tee /etc/resolv.conf > /dev/null"
  end

end